create database 223814706_prueba;
use 223814706_prueba;
show databases;
show tables;
create table Tabla1 (Nombre varchar(255), Apellido varchar(255));
show tables;
drop table Tabla1;
drop database 223814706_prueba;
show databases;
create database 223814706_prod;
use 223814706_prod;
create table clientes_prod (nombre varchar(255), apellido varchar(255), domicilio varchar(255), telefono int, email varchar(255), apodo varchar(255));
show tables;
insert into clientes_prod (nombre, apellido, domicilio, telefono, email, apodo) values ('Juan', 'perez', 'calle 5', 1234333333, 'juanperez@correo.com', 'jperez');
insert into clientes_prod (nombre, apellido, domicilio, telefono, email, apodo) values ('emilia', 'tejana', 'calle 25', 1234333334, 'cameliatejana@correo.com', 'ctejana');
insert into clientes_prod (nombre, apellido, domicilio, telefono, email, apodo) values ('Ermenegildo', 'pacheco', 'calle 87', 1234333335, 'epacheco@correo.com', 'epacheco');
insert into clientes_prod (nombre, apellido, domicilio, telefono, email, apodo) values ('Tomas', 'Valverde', 'calle 1', 1234333336, 'tomasvalverde@correo.com', 'tverde');
insert into clientes_prod (nombre, apellido, domicilio, telefono, email, apodo) values ('Kevin', 'Marsh', 'calle 11', 1234333337, 'kmarsh@correo.com', 'kmarsh');
select * from clientes_prod;
drop database 223814706_prod;
show databases;
